### PR TITLE
Change _unindent to unindent

### PR DESCRIPTION
**Pull request by chuckh**
`unindent` has landed:

// TODO(noms): When marked-element/issues/23 lands, this will become
// a public method and will need to be updated.

see pr https://github.com/PolymerElements/marked-element/pull/25
see pr https://github.com/PolymerElements/marked-element/issues/23

### CODE REVIEW

**Comment by notwaldorf** [comment]
Still needs https://github.com/PolymerElements/marked-element/pull/29 to land

**Comment by chuckh** [comment]
The name has already been changed to `unindent` from `_unindent` here: https://github.com/PolymerElements/marked-element/pull/25/files#diff-f0b9e140535ccafe29cfe484f7fc4a11R160.

So now you will get an error when calling  `var snippet = this.$.marked._unindent(template.innerHTML);` . This should fix that error.

When PolymerElements/marked-element#29 lands it will fix functionality.

**Comment by notwaldorf** [comment]
Yes, but I'm not going to merge this knowing that it will break the repo. It will be merged only after PolymerElements/marked-element#29  is merged :)

**Comment by chuckh** [comment]
I agree we don't want to break the repo. :smiley:

**Comment by notwaldorf** [comment]
Why are the tests grumpy? :(

**Comment by chuckh** [comment]
The grumpy tests where because the `paper-styles` version in `bower.json`. I rebased to fixed that.

**Comment by notwaldorf** [comment]
Hurray! Thanks so much! 🍰

**Pull request merged**
