### PR TITLE
Added support for is="dom-bind" allowing for databinding within demo snippet

### LINKED ISSUE #31: demo-snippet doesn't support is="dom-bind"
### Description
Adding is="dom-bind" causes a duplicate template to appear.

### Expected outcome
image

### Actual outcome
image

### Live Demo
Example: https://jsbin.com/laseditone/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

I'm guessing this effects all major browsers since it's an issue with how demo-snippet handles the template. However I can't verify this since I'm running Ubuntu.

### PR DESCRIPTION
**Pull request by nick-woodward**
Fixed #31 

[Live Demo](https://jsbin.com/yedilumiga/1/edit?html,output)

### CODE REVIEW

**Comment by mercmobily** [comment]
This is such a tiny fix, and it makes such a huge difference! I am currently patching things by hand to make sure templates don't get stamped twice. Please merge this if you don't see any horrible side effects!

**Comment by nick-woodward** [comment]
@mercmobily I'm not entirely sure who all the maintainers are on this repository otherwise I'd ping them.

@notwaldorf who are the active maintainers on this repository?

**Comment by notwaldorf** [comment]
I'll take a look at this today!

**Comment by notwaldorf** [comment]
Hmm why does that work? Don't you need to still stamp the template to render the output?

**Comment by nick-woodward** [comment]
I need to verify, but I get the feeling its functionality specific to each of the template extensions.
https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-bind.html#L97

**Comment by nick-woodward** [comment]
Just verified that _insertChildren and _removeChildren is effectively "stamping" the template for us.

`dom-repeat` and `dom-if` also do stamping, however its conditional based on if there are elements in the array or if the criteria is met.

**Comment by notwaldorf** [comment]
Thanks!

**Comment by shannonmoeller** [comment]
This issues still exists for me when the demo-snippet is rendered in the iron-component-pages iframe.

**Pull request merged**
