### PR TITLE
Create iron-demo-helpers.html

### PR DESCRIPTION
**Pull request by marcus7777**
to make docs

### CODE REVIEW

**Comment by notwaldorf** [comment]
I don't think this would actually make docs, would it? The `bower.json` main points to `demo-snippet.html`, which I think is what the catalog uses? /cc @arthurevans 

Also, as a general comment, this file doesn't follow the convention of having the Polymer license at the top

**Comment by arthurevans** [comment]
I see docs here: https://elements.polymer-project.org/elements/iron-demo-helpers

**Comment by notwaldorf** [comment]
Closing, then, since this isn't fixing anything. Please re-open if you can provide more information about why this is needed

**Comment by marcus7777** [comment]
compare here
https://elements.polymer-project.org/bower_components/iron-demo-helpers/
to
https://elements.polymer-project.org/bower_components/paper-input/
documents are be made by index.html which is not reading The Bower.json file.

**Pull request closed without merging**
